site_name: 'mailcow: dockerized documentation'
site_url: https://mailcow.github.io/mailcow-dockerized-docs/
copyright: "Copyright &copy; 2022 Servercow Team & Community"
repo_name: mailcow/mailcow-dockerized
repo_url: https://github.com/mailcow/mailcow-dockerized
edit_uri: ../mailcow-dockerized-docs/edit/master/docs/
remote_branch: gh-pages

theme:
  name: material
  palette:
   - media: "(prefers-color-scheme: light)"
     scheme: default
     toggle:
       icon: material/toggle-switch-off-outline 
       name: Dark Mode
   - media: "(prefers-color-scheme: dark)"    
     scheme: slate 
     toggle:
       icon: material/toggle-switch
       name: Light Mode
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.top
    - navigation.tracking
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.extra
  - footnotes    

nav:
  - 'Information & Support': 'index.md'
  - 'Prerequisites':
    - 'Prepare your system': 'prerequisite/prerequisite-system.md'
    - 'DNS setup': 'prerequisite/prerequisite-dns.md'
  - 'Installation, Update & Migration':
    - 'Installation': 'i_u_m/i_u_m_install.md'
    - 'Update': 'i_u_m/i_u_m_update.md'
    - 'Migration': 'i_u_m/i_u_m_migration.md'
    - 'Deinstallation': 'i_u_m/i_u_m_deinstall.md'
  - 'Post Installation Tasks':
    - 'Advanced SSL': 'post_installation/firststeps-ssl.md'
    - 'Disable IPv6': 'post_installation/firststeps-disable_ipv6.md'
    - 'DMARC Reporting': 'post_installation/firststeps-dmarc_reporting.md'
    - 'IP bindings': 'post_installation/firststeps-ip_bindings.md'
    - 'Local MTA on Docker host': 'post_installation/firststeps-local_mta.md'
    - 'Logging': 'post_installation/firststeps-logging.md'
    - 'Reverse Proxy': 'post_installation/firststeps-rp.md'
    - 'Rspamd UI': 'post_installation/firststeps-rspamd_ui.md'
    - 'SNAT': 'post_installation/firststeps-snat.md'
    - 'Sync job migration': 'post_installation/firststeps-sync_jobs_migration.md'
  - 'Models':
    - 'ACL': 'models/model-acl.md'
    - 'Password hashing': 'models/model-passwd.md'
    - 'Sender and receiver model': 'models/model-sender_rcv.md'
  - 'General Troubleshooting':
    - 'Introduction': 'troubleshooting/debug.md'
    - 'Admin login to SOGo': 'troubleshooting/debug-admin_login_sogo.md'
    - 'Advanced: Find memory leaks in Rspamd': 'troubleshooting/debug-rspamd_memory_leaks.md'
    - 'Attach to a Container': 'troubleshooting/debug-attach_service.md'
    - 'Common Problems': 'troubleshooting/debug-common_problems.md'
    - 'Logs': 'troubleshooting/debug-logs.md'
    - 'Manual MySQL upgrade': 'troubleshooting/debug-mysql_upgrade.md'
    - 'Recover crashed Aria storage engine': 'troubleshooting/debug-mysql_aria.md'
    - 'Remove Persistent Data': 'troubleshooting/debug-rm_volumes.md'
    - 'Reset Passwords (incl. SQL)': 'troubleshooting/debug-reset_pw.md'
    - 'Reset TLS certificates': 'troubleshooting/debug-reset_tls.md'
  - 'Backup & Restore':
    - 'Component backup & restore':
      - 'Backup': 'backup_restore/b_n_r-backup.md'
      - 'Restore': 'backup_restore/b_n_r-restore.md'
    - 'Cold-standby (rolling backup)': 'backup_restore/b_n_r-coldstandby.md'
    - 'Manual backups':
      - 'Maildir': 'backup_restore/b_n_r-backup_restore-maildir.md'
      - 'MySQL (mysqldump)': 'backup_restore/b_n_r-backup_restore-mysql.md'
    - 'mailcow-internal backups':
      - 'Recover accidentally deleted data': 'backup_restore/b_n_r-accidental_deletion.md'
  - 'Manual/Guides/Examples':
    - 'mailcow UI':
      - 'Blacklist / Whitelist': 'manual-guides/mailcow-UI/u_e-mailcow_ui-bl_wl.md'
      - 'Configuration': 'manual-guides/mailcow-UI/u_e-mailcow_ui-config.md'
      - 'CSS overrides': 'manual-guides/mailcow-UI/u_e-mailcow_ui-css.md'
      - 'Pushover': 'manual-guides/mailcow-UI/u_e-mailcow_ui-pushover.md'
      - 'Spamfilter': 'manual-guides/mailcow-UI/u_e-mailcow_ui-spamfilter.md'
      - 'Tagging': 'manual-guides/mailcow-UI/u_e-mailcow_ui-tagging.md'
      - 'Temporary email aliases': 'manual-guides/mailcow-UI/u_e-mailcow_ui-spamalias.md'
      - 'Two-Factor Authentication': 'manual-guides/mailcow-UI/u_e-mailcow_ui-tfa.md'
      - 'WebAuthn / FIDO2': 'manual-guides/mailcow-UI/u_e-mailcow_ui-fido.md'
    - 'Postfix':
      - 'Add trusted networks': 'manual-guides/Postfix/u_e-postfix-trust_networks.md'
      - 'Custom transport maps': 'manual-guides/Postfix/u_e-postfix-custom_transport.md'
      - 'Customize/Expand main.cf': 'manual-guides/Postfix/u_e-postfix-extra_cf.md'
      - 'Disable Sender Addresses Verification': 'manual-guides/Postfix/u_e-postfix-disable_sender_verification.md'
      - 'Max. message size (attachment size)': 'manual-guides/Postfix/u_e-postfix-attachment_size.md'
      - 'Relayhosts': 'manual-guides/Postfix/u_e-postfix-relayhost.md'
      - 'Statistics with pflogsumm': 'manual-guides/Postfix/u_e-postfix-pflogsumm.md'
      - 'Whitelist IP in Postscreen': 'manual-guides/Postfix/u_e-postfix-postscreen_whitelist.md'
    - 'Unbound':
      - 'Using an external DNS service': 'manual-guides/Unbound/u_e-unbound-fwd.md'
    - 'Dovecot':
      - 'Customize/Expand dovecot.conf': 'manual-guides/Dovecot/u_e-dovecot-extra_conf.md'
      - 'Enable "any" ACL settings': 'manual-guides/Dovecot/u_e-dovecot-any_acl.md'
      - 'Expunge a Users mails': 'manual-guides/Dovecot/u_e-dovecot-expunge.md'
      - 'FTS (Solr)': 'manual-guides/Dovecot/u_e-dovecot-fts.md'
      - 'IMAP IDLE interval': 'manual-guides/Dovecot/u_e-dovecot-idle_interval.md'
      - 'Mail crypt': 'manual-guides/Dovecot/u_e-dovecot-mail-crypt.md'
      - 'More Examples with DOVEADM': 'manual-guides/Dovecot/u_e-dovecot-more.md'
      - 'Move Maildir (vmail)': 'manual-guides/Dovecot/u_e-dovecot-vmail-volume.md'
      - 'Public folders': 'manual-guides/Dovecot/u_e-dovecot-public_folder.md'
      - 'Static master user': 'manual-guides/Dovecot/u_e-dovecot-static_master.md'
      - 'Vacation replies for catchall addresses': 'manual-guides/Dovecot/u_e-dovecot-catchall_vacation.md'
    - 'Nginx':
      - 'Create subdomain webmail.example.org': 'manual-guides/Nginx/u_e-nginx_webmail-site.md'
      - 'Custom sites': 'manual-guides/Nginx/u_e-nginx_custom.md'
    - 'Watchdog':
      - 'Thresholds': 'manual-guides/Watchdog/u_e-watchdog-thresholds.md'
    - 'Redis': 'manual-guides/Redis/u_e-redis.md'
    - 'Rspamd': 'manual-guides/Rspamd/u_e-rspamd.md'
    - 'SOGo': 'manual-guides/SOGo/u_e-sogo.md'
    - 'Docker':
      - 'Customize Dockerfiles': 'manual-guides/Docker/u_e-docker-cust_dockerfiles.md'
      - 'Docker Compose Bash Completion': 'manual-guides/Docker/u_e-docker-dc_bash_compl.md'
    - 'Why unbound?': 'manual-guides/u_e-why_unbound.md'
    - 'Autodiscover / Autoconfig': 'manual-guides/u_e-autodiscover_config.md'
    - 'Redirect HTTP to HTTPS': 'manual-guides/u_e-80_to_443.md'
    - 'Re-enable TLS 1.0 and TLS 1.1': 'manual-guides/u_e-reeanble-weak-protocols.md'
    - "Run scripts before and after updates": "manual-guides/u_e-update-hooks.md"
  - 'Client Configuration':
    - 'Overview': 'client/client.md'
    - 'Android': 'client/client-android.md'
    - 'Apple macOS / iOS': 'client/client-apple.md'
    - 'eM Client': 'client/client-emclient.md'
    - 'KDE Kontact': 'client/client-kontact.md'
    - 'Microsoft Outlook': 'client/client-outlook.md'
    - 'Mozilla Thunderbird': 'client/client-thunderbird.md'
    - 'Windows Mail': 'client/client-windows.md'
    - 'Manual configuration': 'client/client-manual.md'
  - 'Third party apps':
    - 'Borgmatic Backup': 'third_party/third_party-borgmatic.md'
    - 'Exchange Hybrid Setup': 'third_party/third_party-exchange_onprem.md'
    - 'Gitea': 'third_party/third_party-gitea.md'
    - 'Gogs': 'third_party/third_party-gogs.md'
    - 'Mailman 3': 'third_party/third_party-mailman3.md'
    - 'Mailpiler Integration': 'third_party/third_party-mailpiler_integration.md'
    - 'Nextcloud': 'third_party/third_party-nextcloud.md'
    - 'Portainer': 'third_party/third_party-portainer.md'
    - 'Roundcube': 'third_party/third_party-roundcube.md'
    
plugins:
  - search
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Europe/Berlin 
  - i18n: # <--- Translation plugin
      default_language: en
      languages:
        en: English
        de: Deutsch
      nav_translations:
      #### Begin of german translation
        de:
          'Information & Support': 'Informationen & Support'
          ### Prerequisites Section
          'Prerequisites': 'Voraussetzungen'
          'Prepare your system': 'Systemvoraussetzungen'
          'DNS setup': 'DNS Einstellungen'
          ### Installation Section
          'Installation, Update & Migration': 'Installation, Update und Migration' 
          ### Post Installation Tasks Section
          'Post Installation Tasks': 'Post-Installationsaufgaben'
          'Advanced SSL': 'Erweitertes SSL'
          'Disable IPv6': 'IPv6 deaktivieren'
          'IP bindings': 'IP-Verbindungen'
          'Local MTA on Docker host': 'Lokaler MTA auf Docker-Host'
          'Sync job migration': 'Migration von Sync-Jobs'
          ### Models Section
          'Models': 'Modelle'
          'Password hashing': 'Passwort-Hashing'
          'Sender and receiver model': 'Sender- und Empfängermodell'
          'General Troubleshooting': 'Allgemeine Fehlersuche'
          'Introduction': 'Einführung'
          'Admin login to SOGo': 'Admin-Anmeldung bei SOGo'
          'Advanced: Find memory leaks in Rspamd': 'Fortgeschritten: Memory-Leaks in Rspamd finden'
          'Attach to a Container' : 'In einen Container wechseln (CLI)'
          'Common Problems': 'Häufig auftretende Probleme'
          'Manual MySQL upgrade': 'Manuelles MySQL-Upgrade'
          'Recover crashed Aria storage engine': 'Abgestürzte Aria-Speicher-Engine wiederherstellen'
          'Remove Persistent Data': 'Persistente Daten löschen'
          'Reset Passwords (incl. SQL)': 'Passwörter zurücksetzen (inkl. SQL)'
          'Reset TLS certificates': 'TLS-Zertifikate zurücksetzen'
          ### Backup & Restore Section
          'Backup & Restore': 'Sichern & Wiederherstellen'
          'Component backup & restore' : 'Sicherung und Wiederherstellung von Komponenten'
          'Backup': 'Sicherung'
          'Restore': 'Wiederherstellung'
          'Cold-standby (rolling backup)' : 'Cold-standby (rollende Sicherung)'
          'Manual backups' : 'Manuelle Sicherung'
          'Maildir' : 'Mail-Verzeichnis'
          'mailcow-internal backups' : 'Interne mailcow Sicherungen'
          'Recover accidentally deleted data' : 'Versehentlich gelöschte Daten wiederherstellen'
          ### Manual/Guides/Examples Section
          'Manual/Guides/Examples': 'Anleitungen/Beispiele'
            ### Mailcow UI Subsection
          'Configuration' : 'Konfiguration'
          'CSS overrides' : 'CSS-Überschreibungen'
          'Tagging' : 'Tagging (Markierungen)'
          'Temporary email aliases' : 'Temporäre E-Mail-Aliase'
          'Two-Factor Authentication' : 'Zwei-Faktoren-Authentifizierung'
            ### Postfix Subsection
          'Add trusted networks': 'Vertrauenswürdige Netzwerke hinzufügen'
          'Custom transport maps': 'Benutzerdefinierte Transportmaps'
          'Customize/Expand main.cf': 'main.cf anpassen/erweitern'
          'Disable Sender Addresses Verification': 'Überprüfung der Absenderadressen deaktivieren'
          'Max. message size (attachment size)': 'Maximale Nachrichtengröße (Größe des Anhangs)'
          'Statistics with pflogsumm': 'Statistik mit pflogsumm'
          'Whitelist IP in Postscreen': 'IP in Postscreen auf die Whitelist setzen'
            ### Unbound Subsection
          'Using an external DNS service': 'Verwendung eines externen DNS-Dienstes'
            ### Dovecot Subsection
          'Customize/Expand dovecot.conf': 'Anpassen/Erweitern von dovecot.conf'
          'Enable "any" ACL settings': 'Aktivierung von "any" ACL-Einstellungen'
          'Expunge a Users mails': 'Löschen der Mails eines Benutzers'
          'IMAP IDLE interval': 'IMAP IDLE-Intervall'
          'More Examples with DOVEADM': 'Weitere Beispiele mit DOVEADM'
          'Move Maildir (vmail)': 'Maildir verschieben (vmail)'
          'Public folders': 'Öffentliche Ordner'
          'Static master user': 'Statischer Hauptbenutzer'
          'Vacation replies for catchall addresses': 'Urlaubsantworten für Catchall-Adressen'
            ### Nginx Subsection
          'Create subdomain webmail.example.org': 'Subdomäne webmail.example.org erstellen'
          'Custom sites': 'Benutzerdefinierte Seiten'
            ### Watchdog Subsection
          'Thresholds': 'Thresholds'
            ### Docker Subsection
          'Customize Dockerfiles': 'Dockerfiles anpassen'
          'Why unbound?': 'Warum unbound?'
          'Redirect HTTP to HTTPS': 'HTTP auf HTTPS umleiten'
          'Re-enable TLS 1.0 and TLS 1.1': 'TLS 1.0 und TLS 1.1 wieder aktivieren'
          'Run scripts before and after updates': 'Skripte vor und nach Aktualisierungen ausführen'
          ### Client Configuration Section
          'Client Configuration': 'Client-Konfiguration'
          'Overview': 'Übersicht'
          'Manual configuration': 'Manuelle Konfiguration'
          ### Third party apps Section
          'Third party apps': 'Anwendungen von Drittanbietern'
          'Borgmatic Backup': 'Borgmatic-Sicherung'
       #### End of german translation

extra:
  social:
    - icon: fontawesome/solid/globe-americas
      link: https://mailcow.email
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mailcow
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mailcow_email
  theme:
    palette:
      primary: indigo
      accent: orange
extra_css: [ assets/stylesheets/extra.css ]
extra_javascript:
  - assets/javascripts/client.js
